### PR TITLE
Make activate set not mess with LOAD_PATH

### LINKED ISSUE #19: Loading packages from the "base" env after `TestEnv.activate` (and useage with ReTest.jl)
I have ReTest.jl in my "base" (v1.6) environment, but it seems that after `TestEnv.activate()` i'm no longer in an env that has ReTest 

e.g.
```julia
julia> Pkg.activate("~/repos/ChainRules.jl/Project.toml")
  Activating environment at `~/repos/ChainRules.jl/Project.toml`

julia> using ReTest  # works

julia> Base.LOAD_PATH
3-element Vector{String}:
 "@"
 "@v#.#"
 "@stdlib"

julia> TestEnv.activate()
"/var/folders/hx/1h0bbkfd18d4n1qrnwmrl4j00000gn/T/jl_240blx/Project.toml"

julia> using ReTest  # oops
ERROR: ArgumentError: Package ReTest not found in current path:
- Run `import Pkg; Pkg.add("ReTest")` to install the ReTest package.

Stacktrace:
 [1] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:893
   
julia> Base.LOAD_PATH
2-element Vector{String}:
 "@"
 "/var/folders/hx/1h0bbkfd18d4n1qrnwmrl4j00000gn/T/jl_240blx"
```

### PR DESCRIPTION
**Pull request by oxinabox**
Should fix #19 .
Does fix it for me.

@nickrobinson251  do you want to take a look and see if it fixes?
This is the branch for julia 1.7, it will need porting to other banches after it is approved

A very nice side bonus of this approach is that `Pkg.activate("originalpath")` actually does indeed remove the test enviroment.

### CODE REVIEW

File: test/activate_set.jl [hunk 1]
```diff
@@ -1,12 +1,18 @@
 @testset "activate_set.jl" begin
     @testset "activate [extras]" begin
         orig_project_toml_path = Base.active_project()
+        push!(LOAD_PATH, mktempdir())  # put something weird in LOAD_PATH for testing
+        orig_load_path = Base.LOAD_PATH
         try
             TestEnv.activate("ChainRulesCore")
             new_project_toml_path = Base.active_project()
             @test new_project_toml_path != orig_project_toml_path
+            @test orig_load_path ⊆ Base.LOAD_PATH
```
Comment (oxinabox) [inline test/activate_set.jl:10]: this could be
```suggestion
            @test orig_load_path == Base.LOAD_PATH
```
but idk if that is a promise i want to make.
Maybe for now it is and then can relax it later?

File: test/activate_set.jl [hunk 2]
```diff
@@ -15,14 +21,18 @@
...
     @testset "activate test/Project" begin
         orig_project_toml_path = Base.active_project()
+        push!(LOAD_PATH, mktempdir())  # put something weird in LOAD_PATH for testing
+        orig_load_path = Base.LOAD_PATH
         try
             # YAXArrays has a test/Project.toml, which contains CSV
             TestEnv.activate("YAXArrays")
             new_project_toml_path = Base.active_project()
             @test new_project_toml_path != orig_project_toml_path
+            @test orig_load_path ⊆ Base.LOAD_PATH
```
Comment (oxinabox) [inline test/activate_set.jl:31]:
```suggestion
            @test orig_load_path == Base.LOAD_PATH
```

?

**Comment by nickrobinson251** [comment]
> @nickrobinson251 do you want to take a look and see if it fixes?
> This is the branch for julia 1.7, ...

Downloaded v1.7.0-beta3.0 just for this... what is this magic?! 😆 

```julia
julia> using TestEnv
 │ Package TestEnv not found, but a package named TestEnv is available from a registry.
 │ Install package?
 │   (@v1.7) pkg> add TestEnv
 └ (y/n) [y]:
``

**Comment by nickrobinson251** [comment]
yes, this fixes the issue for me too 😀

File: test/activate_set.jl (hunk 1 above)
Comment (nickrobinson251) [reply test/activate_set.jl:10]: i think `==`  makes sense, but idk i've never really worked much with Pkg internals

**Review by nickrobinson251 — APPROVED** [review]

**Comment by nickrobinson251** [comment]
(btw, this fixes the issue i actually opened, it doesn't get all the way to ReTest.jl working with TestEnv, i'll open a new issue)
